### ISSUE TITLE
Black mesh out of bounds at ceiling height

### ISSUE THREAD

**Issue by Cyklan** [CodeArcade/GameOff2021#3]
- [ ] Generate multiple black meshes around the edge of the ceiling of walls
This prevents the user from being able to see the backside of walls and hides the fact that the dungeon is simply floating in the air
Example image:
![grafik](https://user-images.githubusercontent.com/37187056/140414876-33b9dec1-ae7f-4fcd-9613-71b652ec9c65.png)

**Comment by NoctusRex** [comment]
Solved issue by increasing wall size and tweaking lighting settings.

![image](https://user-images.githubusercontent.com/48673579/140606356-b7592e04-c94d-48a6-b868-3285565a73ed.png)
![image](https://user-images.githubusercontent.com/48673579/140606368-c095bbcf-00cd-4f2a-8bd9-c839b2819420.png)
