### ISSUE TITLE
Wider corridors

### ISSUE THREAD

**Issue by Cyklan** [CodeArcade/GameOff2021#4]
The current corridors seem a bit narrow. 
Reasons why it should be changed:
- Enemies or the player could get stuck
- There is no room for dodging attacks
- It would leave most of the screen black

**Comment by NoctusRex** [comment]
The current path size is 1 + (2 * 6 to 9 tiles).
Min = 13
Max = 19

Is this big enough?

![image](https://user-images.githubusercontent.com/48673579/140481669-a7ef2967-661e-4ece-bda4-c837a67ce5e2.png)

**Comment by Cyklan** [comment]
LGTM 👍
