### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by Cyklan** [CodeArcade/GameOff2021#9]
- [x] Enemy AI only enables if player is close enough
- [x] Once enabled, enemies will forever try to attack the player
- [x] melee attackers will move close to player
- [x] ranged attackers will only move into range to attack
- [ ] when attacking, enemies will stop moving for the duration of the attack
- [ ] enemy may drop loot on death

Add enemy ideas and what type of attacker they are / what kind of loot they could drop in the comments

**Comment by Cyklan** [comment]
I've had another optimization idea.

Maybe we only spawn enemies once the player is in a certain range to the enemies. Then enemies could theoretically be pooled to save on memory and cpu usage

**Comment by NoctusRex** [comment]
I did a similar thing.

All spawned enemies will be disabled by default. 
If the player is close to them they get enabled.
Once the player is to far away the enemies get disabled again.

I also tried doing that with the ground and walls, but there were to many objects so performance was even worse.
